# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-11 13:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_search_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StockDailyFifteen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening', models.DecimalField(decimal_places=8, max_digits=10)),
                ('closing', models.DecimalField(decimal_places=8, max_digits=10)),
                ('high', models.DecimalField(decimal_places=8, max_digits=10)),
                ('low', models.DecimalField(decimal_places=8, max_digits=10)),
                ('volume', models.DecimalField(decimal_places=8, max_digits=10)),
                ('timestamp', models.DateTimeField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Stock')),
            ],
        ),
        migrations.CreateModel(
            name='StockDailyFive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening', models.DecimalField(decimal_places=8, max_digits=10)),
                ('closing', models.DecimalField(decimal_places=8, max_digits=10)),
                ('high', models.DecimalField(decimal_places=8, max_digits=10)),
                ('low', models.DecimalField(decimal_places=8, max_digits=10)),
                ('volume', models.DecimalField(decimal_places=8, max_digits=10)),
                ('timestamp', models.DateTimeField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Stock')),
            ],
        ),
        migrations.CreateModel(
            name='StockDailyThirty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening', models.DecimalField(decimal_places=8, max_digits=10)),
                ('closing', models.DecimalField(decimal_places=8, max_digits=10)),
                ('high', models.DecimalField(decimal_places=8, max_digits=10)),
                ('low', models.DecimalField(decimal_places=8, max_digits=10)),
                ('volume', models.DecimalField(decimal_places=8, max_digits=10)),
                ('timestamp', models.DateTimeField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Stock')),
            ],
        ),
        migrations.CreateModel(
            name='StockMonthly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening', models.DecimalField(decimal_places=8, max_digits=10)),
                ('closing', models.DecimalField(decimal_places=8, max_digits=10)),
                ('high', models.DecimalField(decimal_places=8, max_digits=10)),
                ('low', models.DecimalField(decimal_places=8, max_digits=10)),
                ('volume', models.DecimalField(decimal_places=8, max_digits=10)),
                ('timestamp', models.DateTimeField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Stock')),
            ],
        ),
        migrations.CreateModel(
            name='StockWeekly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening', models.DecimalField(decimal_places=8, max_digits=10)),
                ('closing', models.DecimalField(decimal_places=8, max_digits=10)),
                ('high', models.DecimalField(decimal_places=8, max_digits=10)),
                ('low', models.DecimalField(decimal_places=8, max_digits=10)),
                ('volume', models.DecimalField(decimal_places=8, max_digits=10)),
                ('timestamp', models.DateTimeField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Stock')),
            ],
        ),
    ]
